services: 
  homer_users:
    image: b4bz/homer
    container_name: homer_users
    volumes:
      - ./config/config.yml:/www/assets/config.yml # Make sure your local config directory exists
    user: 1000:1000 # default
    networks:
      - proxy
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
      - APP_GROUP=Content
      - APP_LOGO=https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png
      - VIRTUAL_HOST=dashboard.pknw1.co.uk
      - VIRTUAL_PORT=8080
    restart: unless-stopped

networks:
  proxy:
    external: true
